#!/bin/sh

PROG=srs
PROG_PATH="/usr/local/$PROG"

MSG_PREFIX=" *"

echo "$MSG_PREFIX start install $PROG"

service srs stop

if [ -d "$PROG_PATH" ] ; then
	rm -rf $PROG_PATH
fi

mkdir -p $PROG_PATH

cp -v -r -n ./conf $PROG_PATH/
cp -v -r -n ./etc $PROG_PATH/
cp -v -r -n ./objs $PROG_PATH/

if [ -f "/etc/init.d/$PROG" ] ; then
	rm -rf /etc/init.d/$PROG
fi

ln -s  /usr/local/srs/etc/init.d/$PROG /etc/init.d/$PROG

service srs start

echo "$MSG_PREFIX install sucess $PROG"
